language: objective-c

before_install:
  - gem install cocoapods -v 0.37.2
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
  - xctool -workspace iOS-REST-API-Explorer.xcworkspace -scheme iOS-REST-API-Explorer -sdk iphonesimulator
